"""Font assets for deckr-fonts. Auto-generated by pack-tools -- do not edit."""
from justmytype.font_catalog import create_catalog as _create_catalog
_catalog = _create_catalog(package=__package__)
def __getattr__(name):
    return getattr(_catalog, name)
